import type { MappedTypeConfig } from "../../core/mapped-types/MappedTypeConfig.js";
import {
  HyperCubicGenerator,
  CenteredHyperOctahedralGenerator,
  CenteredHyperTetrahedronGenerator,
  FiveDimensionalMgonalPyramidalGenerator,
  FourDimensionalMgonalPyramidalGenerator,
  HyperDodecahedralGenerator,
  HyperIcosahedralGenerator,
  HyperOctahedralGenerator,
  KDimensionalCenteredHyperCubeGenerator,
  KDimensionalHyperCubeGenerator,
  KDimensionalHyperTetrahedronGenerator,
  NexusGenerator,
  HyperTetrahedralGenerator,
  PolyOctahedralGenerator,
  SixDimensionalMgonalPyramidalGenerator,
  CenteredHyperCubeGenerator,
  KDimensionalMgonalPyramidalGenerator,
  KDimensionalHyperOctahedronGenerator,
  KDimensionalCenteredHyperTetrahedronGenerator,
  KDimensionalCenteredHyperOctahedronGenerator,
  KDimensionalHyperTetrahedronSpecificGenerator,
  KDimensionalHyperCubeSpecificGenerator,
  KDimensionalHyperOctahedronSpecificGenerator,
  KDimensionalCenteredHyperTetrahedronSpecificGenerator,
  KDimensionalCenteredHyperCubeSpecificGenerator,
  KDimensionalCenteredHyperOctahedronSpecificGenerator,
} from "../strategies/index.js";

const baseStrategies = {
  hyperTetrahedral: new HyperTetrahedralGenerator(),
  hyperCubic: new HyperCubicGenerator(),
  hyperOctahedral: new HyperOctahedralGenerator(),
  hyperDodecahedral: new HyperDodecahedralGenerator(),
  hyperIcosahedral: new HyperIcosahedralGenerator(),
  polyOctahedral: new PolyOctahedralGenerator(),

  kDimensionalHyperTetrahedron: new KDimensionalHyperTetrahedronGenerator(),
  kDimensionalHyperCube: new KDimensionalHyperCubeGenerator(),
  kDimensionalHyperOctahedron: new KDimensionalHyperOctahedronGenerator(),

  kDimensionalMgonalPyramidal: new KDimensionalMgonalPyramidalGenerator(),
  fiveDimensionalMgonalPyramidal: new FiveDimensionalMgonalPyramidalGenerator(),
  fourDimensionalMgonalPyramidal: new FourDimensionalMgonalPyramidalGenerator(),
  sixDimensionalMgonalPyramidal: new SixDimensionalMgonalPyramidalGenerator(),

  centeredHyperTetrahedron: new CenteredHyperTetrahedronGenerator(),
  kDimensionalCenteredHyperTetrahedron: new KDimensionalCenteredHyperTetrahedronGenerator(),

  centeredHyperCube: new CenteredHyperCubeGenerator(),
  kDimensionalCenteredHyperCube: new KDimensionalCenteredHyperCubeGenerator(),

  centeredHyperOctahedral: new CenteredHyperOctahedralGenerator(),
  kDimensionalCenteredHyperOctahedron: new KDimensionalCenteredHyperOctahedronGenerator(),

  nexus: new NexusGenerator(),
};

const alias4DRegularPolytopes = {
  pentatope: baseStrategies.hyperTetrahedral,
  biquadratic: baseStrategies.hyperCubic,
  tesseract: baseStrategies.hyperCubic,
  "5-cell": baseStrategies.hyperTetrahedral,
  "8-cell": baseStrategies.hyperCubic,
  "16-cell": baseStrategies.hyperOctahedral,
  "120-cell": baseStrategies.hyperDodecahedral,
  "600-cell": baseStrategies.hyperIcosahedral,
  "24-cell": baseStrategies.polyOctahedral,
  pentachoron: baseStrategies.hyperTetrahedral,
  octachoron: baseStrategies.hyperCubic,
  hexadecachoron: baseStrategies.hyperOctahedral,
  hecatonicosachoron: baseStrategies.hyperDodecahedral,
  hexacosichoron: baseStrategies.hyperIcosahedral,
  icositetrachoron: baseStrategies.polyOctahedral,
};

const kDimensionalHyperTetrahedronSpecificStrategies = {
  "5-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(5n),
  "6-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(6n),
  "7-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(7n),
  "8-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(8n),
  "9-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(9n),
  "10-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(10n),
  "11-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(11n),
  "12-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(12n),
  "13-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(13n),
  "14-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(14n),
  "15-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(15n),
  "16-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(16n),
  "17-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(17n),
  "18-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(18n),
  "19-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(19n),
  "20-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(20n),
  "21-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(21n),
  "22-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(22n),
  "23-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(23n),
  "24-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(24n),
  "25-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(25n),
  "26-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(26n),
  "27-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(27n),
  "28-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(28n),
  "29-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(29n),
  "30-simplex": new KDimensionalHyperTetrahedronSpecificGenerator(30n),
};

const kDimensionalHyperCubeSpecificStrategies = {
  "5-hypercube": new KDimensionalHyperCubeSpecificGenerator(5n),
  "6-hypercube": new KDimensionalHyperCubeSpecificGenerator(6n),
  "7-hypercube": new KDimensionalHyperCubeSpecificGenerator(7n),
  "8-hypercube": new KDimensionalHyperCubeSpecificGenerator(8n),
  "9-hypercube": new KDimensionalHyperCubeSpecificGenerator(9n),
  "10-hypercube": new KDimensionalHyperCubeSpecificGenerator(10n),
  "11-hypercube": new KDimensionalHyperCubeSpecificGenerator(11n),
  "12-hypercube": new KDimensionalHyperCubeSpecificGenerator(12n),
  "13-hypercube": new KDimensionalHyperCubeSpecificGenerator(13n),
  "14-hypercube": new KDimensionalHyperCubeSpecificGenerator(14n),
  "15-hypercube": new KDimensionalHyperCubeSpecificGenerator(15n),
  "16-hypercube": new KDimensionalHyperCubeSpecificGenerator(16n),
  "17-hypercube": new KDimensionalHyperCubeSpecificGenerator(17n),
  "18-hypercube": new KDimensionalHyperCubeSpecificGenerator(18n),
  "19-hypercube": new KDimensionalHyperCubeSpecificGenerator(19n),
  "20-hypercube": new KDimensionalHyperCubeSpecificGenerator(20n),
  "21-hypercube": new KDimensionalHyperCubeSpecificGenerator(21n),
  "22-hypercube": new KDimensionalHyperCubeSpecificGenerator(22n),
  "23-hypercube": new KDimensionalHyperCubeSpecificGenerator(23n),
  "24-hypercube": new KDimensionalHyperCubeSpecificGenerator(24n),
  "25-hypercube": new KDimensionalHyperCubeSpecificGenerator(25n),
  "26-hypercube": new KDimensionalHyperCubeSpecificGenerator(26n),
  "27-hypercube": new KDimensionalHyperCubeSpecificGenerator(27n),
  "28-hypercube": new KDimensionalHyperCubeSpecificGenerator(28n),
  "29-hypercube": new KDimensionalHyperCubeSpecificGenerator(29n),
  "30-hypercube": new KDimensionalHyperCubeSpecificGenerator(30n),
};

const kDimensionalHyperOctahedronSpecificStrategies = {
  "5-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(5n),
  "6-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(6n),
  "7-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(7n),
  "8-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(8n),
  "9-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(9n),
  "10-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(10n),
  "11-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(11n),
  "12-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(12n),
  "13-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(13n),
  "14-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(14n),
  "15-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(15n),
  "16-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(16n),
  "17-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(17n),
  "18-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(18n),
  "19-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(19n),
  "20-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(20n),
  "21-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(21n),
  "22-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(22n),
  "23-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(23n),
  "24-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(24n),
  "25-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(25n),
  "26-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(26n),
  "27-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(27n),
  "28-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(28n),
  "29-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(29n),
  "30-cross-polytope": new KDimensionalHyperOctahedronSpecificGenerator(30n),
};

const kDimensionalCenteredHyperTetrahedronSpecificStrategies = {
  "5-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(5n),
  "6-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(6n),
  "7-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(7n),
  "8-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(8n),
  "9-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(9n),
  "10-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(10n),
  "11-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(11n),
  "12-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(12n),
  "13-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(13n),
  "14-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(14n),
  "15-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(15n),
  "16-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(16n),
  "17-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(17n),
  "18-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(18n),
  "19-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(19n),
  "20-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(20n),
  "21-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(21n),
  "22-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(22n),
  "23-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(23n),
  "24-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(24n),
  "25-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(25n),
  "26-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(26n),
  "27-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(27n),
  "28-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(28n),
  "29-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(29n),
  "30-centered-hypertetrahedron": new KDimensionalCenteredHyperTetrahedronSpecificGenerator(30n),
};

const kDimensionalCenteredHyperCubeSpecificStrategies = {
  "5-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(5n),
  "6-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(6n),
  "7-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(7n),
  "8-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(8n),
  "9-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(9n),
  "10-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(10n),
  "11-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(11n),
  "12-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(12n),
  "13-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(13n),
  "14-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(14n),
  "15-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(15n),
  "16-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(16n),
  "17-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(17n),
  "18-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(18n),
  "19-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(19n),
  "20-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(20n),
  "21-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(21n),
  "22-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(22n),
  "23-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(23n),
  "24-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(24n),
  "25-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(25n),
  "26-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(26n),
  "27-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(27n),
  "28-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(28n),
  "29-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(29n),
  "30-centered-hypercube": new KDimensionalCenteredHyperCubeSpecificGenerator(30n),
};

const kDimensionalCenteredHyperOctahedronSpecificStrategies = {
  "5-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(5n),
  "6-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(6n),
  "7-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(7n),
  "8-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(8n),
  "9-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(9n),
  "10-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(10n),
  "11-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(11n),
  "12-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(12n),
  "13-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(13n),
  "14-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(14n),
  "15-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(15n),
  "16-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(16n),
  "17-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(17n),
  "18-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(18n),
  "19-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(19n),
  "20-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(20n),
  "21-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(21n),
  "22-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(22n),
  "23-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(23n),
  "24-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(24n),
  "25-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(25n),
  "26-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(26n),
  "27-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(27n),
  "28-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(28n),
  "29-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(29n),
  "30-centered-hyperoctahedron": new KDimensionalCenteredHyperOctahedronSpecificGenerator(30n),
};

export const MULTIDIMENSIONAL_MAP_STRATEGY = {
  ...baseStrategies,
  ...alias4DRegularPolytopes,
  ...kDimensionalHyperTetrahedronSpecificStrategies,
  ...kDimensionalHyperCubeSpecificStrategies,
  ...kDimensionalHyperOctahedronSpecificStrategies,
  ...kDimensionalCenteredHyperTetrahedronSpecificStrategies,
  ...kDimensionalCenteredHyperCubeSpecificStrategies,
  ...kDimensionalCenteredHyperOctahedronSpecificStrategies,
} as const;

export type MultiDimensionalConfigMap = MappedTypeConfig<typeof MULTIDIMENSIONAL_MAP_STRATEGY>;
