import type { MappedTypeConfig } from "../../core/mapped-types/MappedTypeConfig.js";
import {
  CenteredDodecahedronGenerator,
  CenteredIcosahedronGenerator,
  CenteredMgonalPyramidalGenerator,
  CenteredMgonalPyramidGenerator,
  CenteredOctahedronGenerator,
  CenteredTruncatedCubeGenerator,
  CenteredTruncatedOctahedronGenerator,
  CenteredTruncatedTetrahedronGenerator,
  CubicGenerator,
  DodecahedralGenerator,
  IcosahedralGenerator,
  MgonalPrismGenerator,
  OctahedralGenerator,
  PyramidalGenerator,
  StellaOctangulaGenerator,
  TetrahedralGenerator,
  TruncatedCubicGenerator,
  TruncatedOctahedralGenerator,
  TruncatedTetrahedralGenerator,
} from "../strategies/index.js";

export const SPACE_MAP_STRATEGY = {
  pyramidal: new PyramidalGenerator(),
  mgonalPrism: new MgonalPrismGenerator(),
  centeredMgonalPyramidal: new CenteredMgonalPyramidalGenerator(),
  centeredMgonalPyramid: new CenteredMgonalPyramidGenerator(),
  centeredTruncatedCube: new CenteredTruncatedCubeGenerator(),
  centeredTruncatedTetrahedron: new CenteredTruncatedTetrahedronGenerator(),
  centeredTruncatedOctahedron: new CenteredTruncatedOctahedronGenerator(),
  cubic: new CubicGenerator(),
  tetrahedral: new TetrahedralGenerator(),
  octahedral: new OctahedralGenerator(),
  dodecahedral: new DodecahedralGenerator(),
  icosahedral: new IcosahedralGenerator(),
  stellaOctangula: new StellaOctangulaGenerator(),
  truncatedCubic: new TruncatedCubicGenerator(),
  truncatedTetrahedral: new TruncatedTetrahedralGenerator(),
  truncatedOctahedral: new TruncatedOctahedralGenerator(),
  centeredDodecahedron: new CenteredDodecahedronGenerator(),
  centeredIcosahedron: new CenteredIcosahedronGenerator(),
  centeredOctahedron: new CenteredOctahedronGenerator(),
} as const;

export type SpaceConfigMap = MappedTypeConfig<typeof SPACE_MAP_STRATEGY>;
